import type { Metadata } from 'next';
import '@/assets/styles/globals.css';
import '@/assets/styles/font.scss';
import Header from '@/components/Header';
import { Toaster } from 'react-hot-toast';
import BottomNav from '@/components/BottomNav';
import Footer from '@/components/Footer';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fa">
            <body>
                <Toaster position="top-center" />
                <Header />
                <BottomNav />
                {children}
                <Footer />
            </body>
        </html>
    );
}
